# Prepare

- name: "{{ inner_service_title }} - validate namespace (required)"
  fail:
    msg: "namespace not specified (expected: 'ext_node')"
  when: inner_service_namespace == ''
  tags: ["no_print"]

- name: "{{ inner_service_title }} - validate namespace (ext_node)"
  fail:
    msg: |
      incorrect namespace
      expected: 'ext_node'
      received: '{{ inner_service_namespace }}'
  when: inner_service_namespace != 'ext_node'
  tags: ["no_print"]

- name: "{{ inner_service_title }} - node - digital ocean - vars"
  set_fact:
    ext_node_title: "{{ inner_service_title }} - node - digital ocean"
    ext_node_params: "{{ inner_service_params }}"
    ext_node_credentials: "{{ inner_service_credentials }}"
    ext_node_contents: "{{ inner_service_contents }}"
    ext_node_state: "{{ inner_service_state }}"
    ext_node_base_dir_prefix: "{{ inner_service_base_dir_prefix }}"
    ext_node_tmp_dir: "{{ inner_service_tmp_dir }}"
    ext_node_result: {}
  tags: ["no_print"]

# Node Main Vars

- name: "{{ ext_node_title }} - main vars"
  set_fact:
    ext_node_main_credentials: "{{ ext_node_credentials.node | default({}) }}"
    ext_node_user_data: "{{ ext_node_contents.user_data | default('') }}"
    ext_node_hosts: []
  tags: ["no_print"]

# Main

- name: "{{ ext_node_title }} - node (outer)"
  include_tasks: "digital_ocean.item.node.yml"
  vars:
    ext_node_item_name: "{{ ext_node_item.name }}"
    ext_node_item_state: >-
      {{
        ext_node_item.absent
        | default(false)
        | ternary('absent', ext_node_state)
      }}
    ext_node_item_title: >-
      {{ ext_node_title }} -
      host [{{ ext_node_item_name }} ({{ ext_node_item_state }})]
  loop: "{{ ext_node_params.replicas }}"
  loop_control:
    loop_var: ext_node_item
    label: "{{ ext_node_item_name }}"
  tags: ["no_print"]

- name: "{{ ext_node_title }} - set result (tmp)"
  set_fact:
    ext_node_result:
      hosts: "{{ ext_node_hosts }}"
  tags: ["no_print"]

# Set Result

- name: "{{ ext_node_title }} - set result"
  set_fact:
    cloud_service_result: "{{ ext_node_result }}"
  tags: ["no_print"]
