root: "credentials"
schemas:
  credentials:
    type: "dict"
    props:
      node:
        schema: "digital_ocean_credentials"
        non_empty: true
  digital_ocean_credentials:
    type: "dict"
    props:
      api_token:
        type: "str"
        non_empty: true
