# Prepare

- name: "{{ inner_service_title }} - validate namespace (required)"
  fail:
    msg: "namespace not specified (expected: 'ext_node')"
  when: inner_service_namespace == ''
  tags: ["no_print"]

- name: "{{ inner_service_title }} - validate namespace (ext_node)"
  fail:
    msg: |
      incorrect namespace
      expected: 'ext_node'
      received: '{{ inner_service_namespace }}'
  when: inner_service_namespace != 'ext_node'
  tags: ["no_print"]

- name: "{{ inner_service_title }} - node - digital ocean - vars"
  set_fact:
    ext_node_title: "{{ inner_service_title }} - node - digital ocean"
    ext_node_params: "{{ inner_service_params }}"
    ext_node_credentials: "{{ inner_service_credentials }}"
    ext_node_state: "{{ inner_service_state }}"
    ext_node_base_dir_prefix: "{{ inner_service_base_dir_prefix }}"
    ext_node_tmp_dir: "{{ inner_service_tmp_dir }}"
    ext_node_result: {}
  tags: ["no_print"]

# Node Main Vars (Replica)

- name: "{{ ext_node_title }} - main vars"
  set_fact:
    ext_node_name: "{{ ext_node_params.name | replace('_', '-') }}"
    ext_node_main_credentials: "{{ ext_node_credentials.node | default({}) }}"
    ext_node_instance_state: >-
      {{ ext_node_params.state | default(ext_node_state, true) }}
  tags: ["no_print"]

# Main

- name: >-
    {{ ext_node_title }} - {{ ext_node_instance_state }}
    droplet - {{ ext_node_name }}
  digital_ocean_droplet:
    unique_name: yes
    oauth_token: "{{ ext_node_main_credentials.api_token }}"
    name: "{{ ext_node_name }}"
    state: "{{ ext_node_instance_state }}"
    region_id: "{{ ext_node_params.region_id }}"
    size_id: "{{ ext_node_params.size_id }}"
    image_id: "{{ ext_node_params.image_id }}"
    wait_timeout: "{{ ext_node_params.wait_timeout | default(300, true) }}"
    private_networking: "true"
    ipv6: "{{ ext_node_params.ipv6 | default(omit, true) }}"
    user_data: "{{ ext_node_params.user_data | default(omit, true) }}"
  register: ext_node_details
  tags: ["no_print_skipped"]

- name: >-
    {{ ext_node_title }} - tag the droplet {{ ext_node_name }}
  digital_ocean_tag:
    api_token: "{{ ext_node_main_credentials.api_token }}"
    resource_id: "{{ ext_node_details.data.droplet.id }}"
    name: "{{ ext_node_item }}"
    state: "present"
  loop: "{{ ext_node_params.tags }}"
  loop_control:
    loop_var: ext_node_item
    label: "{{ ext_node_name }} - {{ ext_node_item }}"
  when: ext_node_instance_state == 'present'
  tags: ["no_print_skipped"]

- name: "{{ ext_node_title }} - set result (tmp)"
  set_fact:
    ext_node_result:
      name: "{{ ext_node_name }}"
      state: "{{ ext_node_instance_state }}"
      private_ip: >-
        {{
          ext_node_droplet.networks.v4
          | selectattr('type', 'equalto', 'private')
          | map(attribute='ip_address') | list | first | default('')
        }}
      public_ipv4: >-
        {{
          ext_node_droplet.networks.v4
          | selectattr('type', 'equalto', 'public')
          | map(attribute='ip_address') | list | first | default('')
        }}
      public_ipv6: >-
        {{
          ext_node_droplet.networks.v6
          | selectattr('type', 'equalto', 'public')
          | map(attribute='ip_address') | list | first | default('')
        }}
  tags: ["no_print"]

# Set Result

- name: "{{ ext_node_title }} - set result"
  set_fact:
    cloud_service_result: "{{ ext_node_result }}"
  tags: ["no_print"]
