- name: >-
    {{ ext_dns_title }} -
    [{{ ext_dns_record_type }}] {{ ext_dns_record }} -
    {{ ext_dns_value | default('') }} ({{ ext_dns_state }})
  cloudflare_dns:
    zone: "{{ ext_dns_zone }}"
    proxied: no
    solo: "{{ ext_dns_solo }}"
    type: "{{ ext_dns_record_type }}"
    record: "{{ ext_dns_record | default(omit, true) }}"
    value: "{{ ext_dns_value | default(omit, true) }}"
    account_email: "{{ ext_dns_main_credentials.email }}"
    account_api_token: "{{ ext_dns_main_credentials.token }}"
    state: "{{ ext_dns_final_state }}"
