- name: "{{ inner_service_title }} - validate namespace"
  fail:
    msg: "namespace not specified (expected: 'ext_dns')"
  when: inner_service_namespace == ''
  tags: ["no_print"]

- name: "{{ inner_service_title }} - validate namespace"
  fail:
    msg: |
      incorrect namespace
      expected: 'ext_dns'
      received: '{{ inner_service_namespace }}'
  when: inner_service_namespace != 'ext_dns'
  tags: ["no_print"]

- name: "{{ inner_service_title | default('') }} - dns - cloudflare"
  set_fact:
    ext_dns_title: "{{ inner_service_title }} - dns - cloudflare"
    ext_dns_params: "{{ inner_service_params }}"
    ext_dns_credentials: >-
      {{
        inner_service_credentials[
          inner_service_params.credential_name | default('dns', true)
        ] | default({})
      }}
    ext_dns_state: "{{ inner_service_state }}"
  tags: ["no_print"]

- name: "{{ ext_dns_title }} - vars"
  set_fact:
    ext_dns_zone: "{{ ext_dns_params.zone }}"
    ext_dns_record_type: "{{ ext_dns_params.dns_type }}"
    ext_dns_record: "{{ ext_dns_params.record }}"
    ext_dns_data_list: "{{ ext_dns_params.data_list }}"
  tags: ["no_print"]

- name: >-
    {{ ext_dns_title }} - create record -
    [{{ ext_dns_record_type }}] {{ ext_dns_record }}
  include_tasks: "cloudflare.record.dns.yml"
  vars:
    ext_dns_value: "{{ ext_dns_item.value }}"
    ext_dns_solo: "{{ ext_dns_index == 0 }}"
    ext_dns_final_state: "present"
  loop: "{{ ext_dns_data_list | default([]) | flatten(levels=1) }}"
  loop_control:
    loop_var: ext_dns_item
    index_var: ext_dns_index
    label: "{{ ext_dns_index }}"
  when: ext_dns_state == 'present'
  tags: ["no_print"]

- name: >-
    {{ ext_dns_title }} - delete record -
    [{{ ext_dns_record_type }}] {{ ext_dns_record }}
  include_tasks: "cloudflare.record.dns.yml"
  vars:
    ext_dns_solo: false
    ext_dns_final_state: "absent"
  when: >-
    (ext_dns_state == 'absent') or
    ((ext_dns_data_list | default([]) | length) == 0)
  tags: ["no_print"]
