# Prepare

- name: "{{ inner_service_title }} - validate namespace (required)"
  fail:
    msg: "namespace not specified (expected: 'ext_dns')"
  when: inner_service_namespace == ''
  tags: ["no_print"]

- name: "{{ inner_service_title }} - validate namespace (ext_dns)"
  fail:
    msg: |
      incorrect namespace
      expected: 'ext_dns'
      received: '{{ inner_service_namespace }}'
  when: inner_service_namespace != 'ext_dns'
  tags: ["no_print"]

- name: "{{ inner_service_title }} - dns - nsupdate - vars"
  set_fact:
    ext_dns_title: "{{ inner_service_title }} - dns - nsupdate"
    ext_dns_params: "{{ inner_service_params }}"
    ext_dns_credentials: "{{ inner_service_credentials }}"
    ext_dns_contents: "{{ inner_service_contents }}"
    ext_dns_state: "{{ inner_service_state }}"
    ext_dns_base_dir_prefix: "{{ inner_service_base_dir_prefix }}"
    ext_dns_tmp_dir: "{{ inner_service_tmp_dir }}"
    ext_dns_result: {}
  tags: ["no_print"]

# Main

- name: "{{ ext_dns_title }} - vars"
  set_fact:
    ext_dns_zone: "{{ ext_dns_params.zone }}"
    ext_dns_record_type: "{{ ext_dns_params.dns_type }}"
    ext_dns_record: "{{ ext_dns_params.record }}"
    ext_dns_values: "{{ ext_dns_params.dns_values }}"
    ext_dns_main_credentials: "{{ inner_service_credentials.dns | default({}) }}"
    ext_dns_ttl: "{{ ext_dns_params.ttl | default('') }}"
    ext_dns_protocol: "{{ ext_dns_params.protocol | default('') }}"
    ext_dns_port: "{{ ext_dns_params.port | default('') }}"
    ext_dns_weight: "{{ ext_dns_params.weight | default('') }}"
  tags: ["no_print"]

- name: >-
    {{ ext_dns_title }} - create record -
    [{{ ext_dns_record_type }}] {{ ext_dns_record }}
  nsupdate:
    key_name: "{{ ext_dns_main_credentials.key_name }}"
    key_secret: "{{ ext_dns_main_credentials.key_secret }}"
    key_algorithm: "{{ ext_dns_main_credentials.key_algorithm }}"
    server: "{{ ext_dns_main_credentials.server }}"
    zone: "{{ ext_dns_zone }}"
    type: "{{ ext_dns_record_type }}"
    record: "{{ ext_dns_record }}"
    value: >-
      {{
        ext_dns_values
        | default([])
        | lrd.cloud.simple_dict_prop_list(prop='value')
        | map(attribute='value')
        | list
      }}
    ttl: "{{ ext_dns_ttl | default(omit, true) }}"
    service: "{{ ext_dns_service | default(omit, true) }}"
    proto: "{{ ext_dns_protocol | default(omit, true) }}"
    port: "{{ ext_dns_port | default(omit, true) }}"
    weight: "{{ ext_dns_weight | default(omit, true) }}"
    state: "{{ ext_dns_state }}"

# Set Result

- name: "{{ ext_dns_title }} - set result"
  set_fact:
    cloud_service_result: "{{ ext_dns_result }}"
  tags: ["no_print"]
