- name: "{{ validator_title }} - fastly dns - validate"
  lrd.ext_cloud.vars:
    identifier: "fastly_dns"
    raw_data:
      state: "present"
      namespace: "{{ validator_item.data.namespace | default('') }}"
      params: "{{ validator_item.data.params | default({}) }}"
      credentials: "{{ validator_item.data.credentials | default({}) }}"
      contents: "{{ validator_item.data.contents | default({}) }}"
  no_log: "{{ env_no_log }}"
