- name: "{{ inner_service_title }} - godaddy dns - vars"
  lrd.ext_cloud.vars:
    identifier: "godaddy_dns"
    raw_data:
      namespace: "ext_dns"
      state: "{{ inner_service_state }}"
      params: "{{ inner_service_params }}"
      credentials: "{{ inner_service_credentials }}"
      contents: "{{ inner_service_contents }}"
  register: ext_dns_data_wrapper
  tags: ["no_print"]

- name: "{{ inner_service_title }} - godaddy dns - action"
  lrd.ext_cloud.actions:
    identifier: "godaddy_dns"
    data: "{{ ext_dns_item }}"
  loop: "{{ ext_dns_data_wrapper.data.list }}"
  loop_control:
    loop_var: ext_dns_item
    label: >-
      [{{ ext_dns_item.state }}]
      {{ ext_dns_item.dns_type }}
      - {{ ext_dns_item.record }}
